# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Allen Garvey | Full-stack Developer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Allen Garvey, full-stack software developer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://allen-garvey.com" # the base hostname & protocol for your site
github_username:  allen-garvey

# Build settings
markdown: kramdown
permalink: projects/:title

exclude:
  - allen-garvey-jekyll.sublime-workspace
  - allen-garvey-jekyll.sublime-project
  - README.md
  - gulpfile.js
  - gulp-config.js
  - package.json
  - node_modules/

# Layout defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
